/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_mintymods_jni_MsmJniWrapper */

#ifndef _Included_info_mintymods_jni_MsmJniWrapper
#define _Included_info_mintymods_jni_MsmJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_mintymods_jni_MsmJniWrapper
 * Method:    processRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_mintymods_jni_MsmJniWrapper_processRequest
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
